# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Eduardo Figarola'
tagline:          'Developer'
description:      'Full Stack Web Developer'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems:             [jekyll-paginate,jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
