# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Eduardo Figarola'
tagline:          'Developer'
description:      'Full Stack Web Developer'
url:              https://eduardo.figarola.mx
baseurl:          /

author:
  name:           Eduardo Figarola
  url:            https://twitter.com/Diabulux

paginate:         5

# Custom vars
version:          2.1.0
plugins:             [jekyll-paginate,jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
